name: Rebase Pull Request

on:
  issue_comment:
    types: [created]

jobs:
  rebase_pull_request:
    name: Rebase Pull Request
    if: github.event.issue.pull_request != '' && github.event.comment.author_association == 'MEMBER' && contains(github.event.comment.body, '@BrewTestBot rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Rebase Pull Request
        uses: cirrus-actions/rebase@b87d48154a87a85666003575337e27b8cd65f691
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
